version: 0.2
# https://docs.aws.amazon.com/codebuild/latest/userguide/sample-nodejs-hw.html

phases:
  install:
    commands:
      - echo Installing NPM dependencies...
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading assets to S3 bucket 'hueydev-alanheuertz-web-static'...
      - aws s3 cp --recursive --acl public-read ./build s3://hueydev-alanheuertz-web-static/
      - echo Upload completed on `date`
artifacts:
  files:
    - build/**/*